# Required, otherwise ggshield considers the file to use the deprecated v1 format
version: 2

secret:
  # Exclude files and paths by globbing
  ignored-paths:
    - "bWAPP/*"

  # Detectors to ignore.
  ignored-detectors: # default: []
    - Generic Password
